import { NotImplemented } from '@feathersjs/errors';
import { NullableId, Params } from '@feathersjs/feathers';
import {
  ServiceSwaggerAddon,
  ServiceSwaggerOptions,
} from 'feathers-swagger/types';
import { Application } from '../../declarations';

interface Data {}

interface ServiceOptions {}

export class Admin implements ServiceSwaggerAddon {
  app: Application;
  options: ServiceSwaggerOptions;

  constructor(options: ServiceOptions = {}, app: Application) {
    this.options = options;
    this.app = app;
  }

  //eslint-disable-next-line @typescript-eslint/no-unused-vars
  async create(data: Data, params?: Params): Promise<any> {
    return new NotImplemented();
  }

  //eslint-disable-next-line @typescript-eslint/no-unused-vars
  async remove(id: NullableId, params: Params): Promise<any> {
    return new NotImplemented();
  }

  docs: ServiceSwaggerOptions = {
    description:
      'Creation and deletion of issuer profiles, used by Agency administrators.',
    idType: 'string',
    refs: {
      createResponse: 'admin_create_response',
      removeResponse: 'empty_body',
    },
    definitions: {
      admin_create_response: {
        title: 'admin',
        type: 'object',
        required: ['name', 'api-key'],
        properties: {
          name: {
            type: 'string',
            description: 'The name of the issuer',
          },
          'api-key': {
            type: 'string',
            description: 'The new api-key generated for this issuer.',
          },
        },
      },
      empty_body: {
        title: 'empty',
        type: 'object',
        required: [],
        properties: {},
      },
    },
    securities: ['all'],
  };

  model = {
    description: 'Base Issuer Model',
    type: 'object',
    required: ['name'],
    properties: {
      id: {
        type: 'string',
        description: 'The issuer identifier generated by the system',
        readOnly: true,
      },
      name: {
        type: 'string',
        description: 'The name of the issuer',
      },
    },
  };
}
